name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      java-version: 17

    steps:
      - name: Check out the project
        uses: actions/checkout@v5
      - name: Set up JDK ${{env.java-version}}
        uses: actions/setup-java@v5
        with:
          java-version: ${{env.java-version}}
          distribution: temurin
          cache: maven
      - name: Run Build
        run: mvn -B package
      - name: Get Jars
        run: mkdir staging && cp target/*.jar staging
      - name: Make Jars Available
        uses: actions/upload-artifact@v4
        with:
          name: Jar Files
          path: staging
